extends Node

var PLAYER_CONTROLS_ACTIVE = true
var CAMERA_CONTROLS_ACTIVE = true
var CAMERA_INVERT_X = false
var CAMERA_INVERT_Y = true
var SHOW_STATE_LABELS = false
var SHOW_DEBUG_TRAJECTORIES = false

